agenda/urls.py
from django.conf.urls import include, url
from django.urls import path
import agenda.views

app_name = 'agenda'


urlpatterns = [
    url(r'^list/$',   agenda.views.list, name='list'),  
    url(r'^create/$', agenda.views.create, name='create'),
    url(r'^update/(?P<id>\d+)$', agenda.views.update, name='update'),
    url(r'^view/(?P<id>\d+)$', agenda.views.view, name='detail'),
    url(r'^(?P<id>[0-9]+)/vote/$', agenda.views.vote, name='vote'),

    path('delete/<int:id>', agenda.views.destroy),  
]

app/urls.py
#from django.conf.urls import *
#from django.conf.urls.static import static
#from django.conf import settings
#from django.conf.urls import include, url
#from django.contrib import admin

from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/',  admin.site.urls),
    url(r'^contato/', include('agenda.urls',    namespace='agenda')),
    url(r'^synesp/',  include('synesp.urls'))

]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

synesp/urls.py
from . import views
from django.conf.urls import url

app_name = 'synesp'
urlpatterns = [
    url(r'^criar/$', views.criar, name='criar')
]

agenda/models.py
import datetime
from django.db import models
from django.utils import timezone



# Create your models here.
class Contato(models.Model):
    nome= models.CharField('Nome', max_length=50, unique=True)
    telefone= models.CharField('Telefone', max_length=15)
    data_criacao= models.DateTimeField('Data')
    data_atualizacao= models.DateTimeField('date updated')
    url = models.URLField()

    def was_published_recently(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.name + ":" + self.telefone

synesp/models.py
from django.db import models

# Create your models here.

agenda/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.utils import timezone
from django.template import loader, Context, RequestContext
from django.db import IntegrityError, transaction
from .models import Contato


def list(request):
    contato_list = Contato.objects.order_by('data_atualizacao')[:5]
    context = {'contato_list': contato_list}
    return render(request, 'contato/index.html', context)

def create(request):
    
    # If this is a post request we insert the Contato

    if request.method == 'POST':
        try:
            p = Contato(nome=request.POST['nome'],
                        telefone=request.POST['telefone'],
                        url=request.POST['url'],
                        data_criacao=timezone.now(),
                        data_atualizacao=timezone.now())
            p.save()
            return  HttpResponseRedirect('/contato/list')
        except IntegrityError: 
            raise Http404('INTEGRIDADE VIOLADA - Problema ao gravar o registro')
    else:

        return render(request, 'contato/criar.html')

def update(request, id):
    # If this is a post request we update the Contato

    try:
        contato = Contato.objects.get(pk=id)
        if request.method == 'POST':
            contato.nome = request.POST['nome']
            contato.telefone = request.POST['telefone']
            contato.url = request.POST['url']
            contato.data_atualizacao =timezone.now()
            contato.save()
            return  HttpResponseRedirect('/contato/list')
        else:           
            context = {'contato': contato}          
            return render(request, 'contato/criar.html', context)

    except Contato.DoesNotExist:
        raise Http404("Question does not exist")
    
def view(request, id):
    try:
        contato = Contato.objects.get(pk=id)
    except Contato.DoesNotExist:
        raise Http404("Question does not exist")
       
    return render(request, 'contato/view.html', {
        'contato': contato,
        'error_message': "You didn't select a choice.",})

def delete(request, id):
    try:
        contato = Contato.objects.get(pk=id)

    except Contato.DoesNotExist:
        raise Http404("Question does not exist")
       
    return render(request, 'contato/view.html', {
        'contato': contato,
        'error_message': "You didn't select a choice.",})

def destroy(request, id):  
    try:
        contato = Contato.objects.get(pk=id)
        contato.delete()  
    except Contato.DoesNotExist:
        raise Http404("Question does not exist") 

    return redirect("/contato/list")  

def vote(request, id):
    return HttpResponse("You're voting on question %s." % id)

synesp/views.py
from django.shortcuts import render
from sinesp_client import SinespClient


# Create your views here.

def criar(request):
    # If this is a post request we insert the person

    result = 1
    if request.method == 'POST':
        sc = SinespClient()
        #sc = SinespClient(proxy_address='127.0.0.1', proxy_port=8000)
        result = sc.search(request.POST['placa'])

    context = { 'resultado': result }
    return render(request, 'synesp/criar.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>CRUD DJANGO - METROS4 - UI</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">     
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-colors.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-rtl.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-icons.min.css">
        <link rel="stylesheet" href=" https://printjs-4de6.kxcdn.com/print.min.css">

        <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
        <!-- /container 
        <script src="{% static "js/jquery-2.1.3.min.js" %}"></script>
        <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"><\/script>')</script>
        <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
        -->
        <!-- /container -->
        <script src="https://cdn.metroui.org.ua/v4.3.2/js/metro.min.js"></script>

        <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
       
 


        <script>
                var  APP_URL ="{% url 'agenda:list' %}" ;
        </script>
    </head>
<body>

    <div class="p-0 no-overflow" style="height: 650px;">
        
        <aside class="sidebar pos-absolute z-2" 
            data-role="sidebar" 
            data-toggle="#sidebar-toggle" 
            data-shift=".shifted-content"
            id="sb1" >
            
            <div class="sidebar-header" data-image="{% static "images/sb-bg-1.jpg" %}" style="background-image: url('{% static "images/sb-bg-1.jpg" %}');">
                <a href="/" class="fg-white sub-action" onclick="Metro.sidebar.close('#sb1'); return false;">
                    <span class="mif-arrow-left mif-2x"></span>
                </a>
                <div class="avatar">
                    <img data-role="gravatar" 
                       data-email="sergey@pimenov.com.ua" 
                       data-role-gravatar="true" 
                       src="//www.gravatar.com/avatar/75d0f7104baad47ed0e96649b905d9bf?size=80&amp;d=mp">
                </div>
                <span class="title fg-white">
                    Projeto python Django 
                </span>
                <span class="subtitle fg-white"> CRUD - contatos</span>
            </div>

            <ul class="sidebar-menu">
                <li>
                    <a><span class="mif-home icon"></span>Home</a>
                </li>
                <li>
                    <a href="{% url 'agenda:list' %}"><span class="mif-books icon">                  
                    </span>Contato</a>
                </li>
                <li>
                    <a><span class="mif-files-empty icon"></span>Examples</a>
                </li>
                <li class="divider"></li>
                <li><a><span class="mif-images icon"></span>Icons</a></li>
            </ul>
        </aside>
        <div class="shifted-content h-100 p-ab">
            <div class="app-bar pos-absolute bg-red z-1" data-role="appbar" id="app-bar-1" data-role-appbar="true">
                <button type="button" class="hamburger menu-down hidden" style="display: none;">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </button>
                <button class="app-bar-item c-pointer" id="sidebar-toggle">
                    <span class="mif-menu fg-white"></span>
                </button>
            </div>

            <div class="h-100 p-8">
                {% block content %}{% endblock content %}          
            </div>
        </div>
    </div>

    <div class="bottom-nav pos-absolute1">
        <button class="button alert large" onclick="AddOnclick()">
            <span class="icon mif-plus"></span>
            <span class="label">Add</span>
        </button>
        <button class="button alert large">
            <span class="icon mif-print"></span>
            <span class="label">Relatórios</span>
        </button>
        <button class="button alert large">
            <span class="icon mif-search"></span>
            <span class="label">Search</span>
        </button>
    </div>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X','auto');ga('send','pageview');


        var AddOnclick = function(){
            window.location.assign( "/contato/create" );
        }
    </script>


</body>
</html>

templates/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>API Contatos</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">     
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-colors.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-rtl.min.css">
        <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-icons.min.css">

        
        <script src="{% static "js/jquery-2.1.3.min.js" %}"></script>
        <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"><\/script>')</script>
        <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
        <!-- /container -->
        <script src="https://cdn.metroui.org.ua/v4.3.2/js/metro.min.js"></script>

        <script>
            
        </script>

</head>
<body>

    <div class="example p-0 no-overflow" style="height: 400px;">
        <aside class="sidebar pos-absolute z-2 on-left sidebar-shadow open" data-role="sidebar" data-toggle="#sidebar-toggle" id="sb1" data-role-sidebar="true">
            
            <div class="sidebar-header" data-image="images/sb-bg-1.jpg" style="background-image: url('images/sb-bg-1.jpg');">
                <a href="/" class="fg-white sub-action" onclick="Metro.sidebar.close('#sb1'); return false;"><span class="mif-arrow-left mif-2x"></span></a>
                <div class="avatar">
                    <img data-role="gravatar" 
                       data-email="sergey@pimenov.com.ua" 
                       data-role-gravatar="true" 
                       src="//www.gravatar.com/avatar/75d0f7104baad47ed0e96649b905d9bf?size=80&amp;d=mp">
                </div>
                <span class="title fg-white">Metro 4 Components Library</span>
                <span class="subtitle fg-white"> 2018 © Sergey Pimenov</span>
            </div>

            <ul class="sidebar-menu">
                <li><a><span class="mif-home icon"></span>Home</a></li>
                <li><a><span class="mif-books icon"></span>Guide</a></li>
                <li><a><span class="mif-files-empty icon"></span>Examples</a></li>
                <li class="divider"></li>
                <li><a><span class="mif-images icon"></span>Icons</a></li>
            </ul>
        </aside>
        <div class="aaa h-100 p-ab">
            <div class="app-bar pos-absolute bg-red z-1" data-role="appbar" id="app-bar-1" data-role-appbar="true">
                <button type="button" class="hamburger menu-down hidden" style="display: none;">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </button>
                <button class="app-bar-item c-pointer" id="sidebar-toggle">
                    <span class="mif-menu fg-white"></span>
                </button>
            </div>

            <div class="h-100 p-4">
                <p class="h1">What is Lorem Ipsum?</p>
                <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
                and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </p>
            </div>
        </div>
    </div>


    <!-- 
    <div data-role="appbar">   
        <div class="app-bar-container">
            <a href="#" class="app-bar-item dropdown-toggle">Always</a>
            <ul class="d-menu" data-role="dropdown">
                <li><a href="#">Windows 10</a></li>
                <li>
                    <a href="#" class="dropdown-toggle">Office 365</a>
                    <ul class="d-menu" data-role="dropdown">
                        <li><a href="#">Windows 10</a></li>
                        <li><a href="#">Office 365</a></li>
                        <li class="divider bg-lightGray"></li>
                        <li><a href="#">Skype</a></li>
                    </ul>
                </li>
                <li class="divider bg-lightGray"></li>
                <li><a href="#">Skype</a></li>
            </ul>
        </div>  
        <ul class="app-bar-menu">
            <li><a href="#">Home</a></li>
            <li>
                <a href="#" class="dropdown-toggle">Products</a>
                <ul class="d-menu" data-role="dropdown">
                    <li><a href="#">Windows 10</a></li>
                    <li><a href="#">Office 365</a></li>
                    <li class="divider bg-lightGray"></li>
                    <li><a href="#">Skype</a></li>
                </ul>
            </li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contacts</a></li>
        </ul>
    </div>
  

    <div class="container mt-4 mb-4" style="height: auto !important; border: 1px solid #C00">       
        <div class="example no-border p-0"></div>
        <h2 class="mt-20">Metro 4 Features</h2>
            <div class="row mt-10">
                
                
                {% block content %}{% endblock content %}


            </div>
         
        
    </div>

    <div class="bottom-nav pos-absolute">
        <button class="button">
            <span class="icon mif-plus"></span>
            <span class="label">Add</span>
        </button>
        <button class="button">
            <span class="icon mif-favorite"></span>
            <span class="label">Favorites</span>
        </button>
        <button class="button">
            <span class="icon mif-search"></span>
            <span class="label">Search</span>
        </button>
    </div>
  -->

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>


    </body>
</html>

templates/contato/criar.html
{% extends "base.html" %}
{% block content %}

<script>
     var url = "/contato/list/";
    var customButtons = [
        {
            html: "<span data-role='hint' data-hint-text='Listar contatos' class='mif-menu'></span>",
            cls: "alert",
            onclick: function(){
                window.location.assign( url );
            }
        },        
        {
            html: "<span data-role='hint' data-hint-text='Imprmir form' class='mif-print'></span>",
            cls: "warning",
            onclick: function(){
                printJS({ printable: 'frmGeral', 
                       type: 'html', 
                       header: 'PrintJS - Formulario de Contato' })
            }
        }
    ];
</script>

<h2 class="mt-2">  
  Inserir <small> Contatos </small>
</h2>



<div class="mb-20" id="ce" >   

    <div data-role="panel"
        data-title-caption="Contatos"
        data-collapsible="true"
        data-custom-buttons="customButtons">

        <form method="post" id="frmGeral" data-role="validator" data-on-error-input="notifyOnErrorInput" data-show-error-hint="false">
            {% csrf_token %}
           
            <div class="content-form" data-text="Agenda">                
                <div class="form-group">
                    <label class="block">Nome</label>                  
                    <input name="nome" 
                        placeholder="Informe o nome"
                        value="{{contato.nome}}"
                        data-validate="required" 
                        data-role="materialinput"
                        type="text">  
                        <span class="invalid_feedback">
                            Informe o Nome
                        </span>               
                </div>
                                           
                <div class="form-group">
                    <label class="block">Telefone</label>                    
                    <input id="telefone" name="telefone" value="{{contato.telefone}}"
                        data-validate="required"
                        placeholder="Telefone (xx) xxxxx-xxxx" 
                        data-role="materialinput"                   
                        type="text">
                        <span class="invalid_feedback">
                            Informe o Telefone
                        </span>
                </div>
    
                <div class="form-group">
                    <label class="block">URL</label>
                    <input id="url" name="url" value="{{contato.url}}"
                        data-validate="required"
                        data-role="materialinput"
                        type="text">
                </div>                            
                    
                <div class="form-group">
                    <input type="hidden" name="id" value="{{contato.id}}">
                    <button  type="submit" class="button success">
                        <span class="mif-checkmark"></span>
                        Gravar
                    </button>
                </div>                                                              
                
            </div>
        </form>
     
    </div>


    
</div>




{% endblock content %}

templates/contato/index.html
{% extends "base.html" %}
{% block content %}


<script>
     var url = "/contato/list/";
     var customButtons = [
        {
            html: "<span data-role='hint' data-hint-text='Incluir registro' class='mif-plus'></span>",
            cls: "success",
            onclick: function(){
                window.location.assign( "/contato/create" );
            }
        },
        {
            html: "<span data-role='hint' data-hint-text='Listar contatos' class='mif-menu'></span>",
            cls: "alert",
            onclick: function(){
                window.location.assign( url );
            }
        },        
        {
            html: "<span data-role='hint' data-hint-text='Imprmir form' class='mif-print'></span>",
            cls: "warning",
            onclick: function(){
                printJS('tblGeral', 'html')
            }
        }
    ];
</script>



<div data-role="panel"
        data-title-caption="Lista de Contatos"
        data-collapsible="true"
        data-custom-buttons="customButtons">

    <!-- 
    <div class="toolbar">
        <a href="{% url 'agenda:create' %}" class="tool-button success text-button">
            Incluir
        </a>
        <div class="split-button ml-20">
            <button class="button">Opçoes</button>
            <button class="split dropdown-toggle"></button>
            <ul class="d-menu" data-role="dropdown">
                <li><a href="#">CSV</a></li>
                <li><a href="#">PDF</a></li>
                <li class="divider"></li>
                <li><a href="#">Excel</a></li>
            </ul>
        </div>
    </div>
    -->



    <div class="table-search-block">
        <div class="input">
            <input type="text" data-role-input="true" data-role="input" class="">
            <div class="button-group">
                <button class="button input-clear-button" tabindex="-1" type="button">
                    <span class="default-icon-cross"></span>
                </button>
            </div>
            <div class="prepend">Search:</div>
        </div>
    </div>
    
    <hr>

    {% if contato_list %}
        <table class="table striped table-border" id="tblGeral" data-role="table1">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>Site</th>
                    <th colspan="3">Opçoes</th>
                </tr>
            </thead>
            <tbody> 
                {% for person in contato_list %}
                <tr>
                    <td>{{person.nome|capfirst }}</td>
                    <td>{{person.telefone}}</td>
                    <td>{{person.url}}</td>
                    <td>
                        <a class="button primary" href="/contato/view/{{person.id}}">
                            <span class="mif-file-empty mif-2x"></span> 
                        </a>
                    </td>
                    <td>
                        <a class="button primary" href="/contato/update/{{person.id}}">
                            <span class="mif-checkmark mif-2x"></span> 
                        </a>
                    </td>
                    <td >
                        <a href="#"  onclick="openDemoDialogActions('{{person.id}}')" class="button alert">
                            <span class="mif-bin mif-2x"></span>                            
                        </a>
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Sem registro</p>
    {% endif %}


</div>

    
    <script>
        function openDemoDialogActions(id){
            var url = "/contato/delete/"+id;
            Metro.dialog.create({
                title: "INFORMAÇÃO?",
                content: "<div>Deseja ralmente exluir o registro...</div>",
                actions: [
                    {
                        caption: "Confirmar",
                        cls: "js-dialog-close alert",
                        onclick: function(){
                            window.location.assign( url );
                        }
                    },
                    {
                        caption: "Cancelar",
                        cls: "js-dialog-close",
                        onclick: function(){
                            alert("You clicked Disagree action");
                        }
                    }
                ]
            });
        }

        var AddOnclick = function(){
                printJS({ printable: 'frmGeral', 
                       type: 'html', 
                       header: 'PrintJS - Formulario de Contato' })
        }


    </script>

{% endblock content %}

templates/contato/view.html
{% extends "base.html" %}
{% block content %}
<script>
    var customButtons = [        
        {
            html: "<span data-role='hint' data-hint-text='Incluir registro' class='mif-plus'></span>",
            cls: "alert",
            onclick: function(){
                window.location.assign( "/contato/create" );
            }
        },
        {
            html: "<span data-role='hint' data-hint-text='Imprmir form' class='mif-print'></span>",
            cls: "warning",
            onclick: function(){
                printJS({ printable: 'frmGeral', 
                       type: 'html', 
                       header: 'PrintJS - Formulario de Contato' })
            }
        }
    ];
</script>
<h2 class="mt-2">  
    Visualizar <small> Contatos </small>
</h2>
  
<div class="mb-20" id="ce" >   

    <div data-role="panel"
        data-title-caption="Contatos"
        data-collapsible="true"
        data-custom-buttons="customButtons">

        <div id="frmGeral"  class="row">
            <div class="cell-8">
                <p>Name:  {{contato.nome}}</p>
            </div>
            
            <div class="cell-8">
                <p>Telefone:  {{contato.telefone}}</p>
            </div>
            
            <div class="cell-8">
                <p>Url:  {{contato.url}}</p>
            </div>
        </div>
     
    </div>


    
</div>


{% endblock content %}

templates/synesp/criar.html
{% extends "base.html" %}
{% block content %}
     <br> <br>
<form method="post">
    {% csrf_token %}
    <label>Placa: </label>
    <input name="placa" value="">



    {{ resultado }}
    <br>
     <input type="hidden" name="id" value="">
    <input type="submit" value="Submit">
</form>
{% endblock content %}